[tool.poetry]
name = "dlta"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
jupyter-book = "^1.0.0"
pandas = "^2.2.0"
gensim = "^4.3.2"
nltk = "^3.8.1"
textblob = "^0.17.1"
pyarrow = "^15.0.0"
scikit-learn = "^1.4.0"
pysentiment2 = "^0.1.1"
matplotlib = "^3.8.2"
plotly = "^5.18.0"
torch = "^2.1.2"
umap-learn = "^0.5.5"
jupyter = "^1.0.0"
ipywidgets = "^8.1.1"
transformers = "^4.37.1"
yfinance = "^0.2.36"
statsmodels = "^0.14.1"
ghp-import = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
